# -*- coding: utf-8 -*-
"""Image_recognition_on_Arm_Cortex_M_with_CMSIS_NN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OxxCFyjauyvY7phgv8sagf_tXgJUS164
"""

!pip install mbed-cli

!pip install mercurial

mkdir CMSISNN_Webinar

cd CMSISNN_Webinar

!mbed new cmsisnn_demo --mbedlib

cd cmsisnn_demo/.temp/tools/

!pip install -r requirements.txt

!pip install jsonschema

!pip install pyelftools

pwd

cd -1

cd cmsisnn_demo

!mbed add http://os.mbed.com/teams/ST/code/BSP_DISCO_F746NG/

!mbed add http://os.mbed.com/teams/ST/code/LCD_DISCO_F746NG

ls

!cat mbed.bld

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mbed.bld
# https://mbed.org/users/mbed_official/code/mbed/builds/e95d10626187

!mbed deploy

cd -1

!git clone https://github.com/ARM-software/ML-examples.git

cd cmsisnn_demo/

!mbed compile -m DISCO_F746NG -t GCC_ARM --source . --source ../ML-examples/cmsisnn-cifar10/camera_demo/camera_app/

cd -2

cd -1

cd -0

mkdir GCC-ARM

cd GCC-ARM

!wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-aarch64-linux.tar.bz2

ls

cd ~

cd /content

ls

cd GCC-ARM

ls

!tar xjf gcc-arm-none-eabi-9-2019-q4-major-aarch64-linux.tar.bz2

ls

!mbed config -G GCC_ARM_PATH "/content/GCC-ARM/gcc-arm-none-eabi-7-2017-q4-major/bin"

!mbed compile -m DISCO_F746NG -t GCC_ARM --source . --source ../ML-examples/cmsisnn-cifar10/camera_demo/camera_app/

cd /content/CMSISNN_Webinar/cmsisnn_demo/.temp/tools

cd cmsisnn_demo

ls

!mbed compile -m DISCO_F746NG -t GCC_ARM --source . --source ../ML-examples/cmsisnn-cifar10/camera_demo/camera_app/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mbed_settings.py
# """
# mbed SDK
# Copyright (c) 2016 ARM Limited
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# """
# 
# from os.path import join, abspath, dirname
# 
# #ROOT = abspath(join(dirname(__file__), "."))
# 
# ##############################################################################
# # Build System Settings
# ##############################################################################
# #BUILD_DIR = abspath(join(ROOT, "build"))
# 
# # ARM
# #ARM_PATH = "../content/GCC-ARM/gcc-arm-none-eabi-9-2019-q4-major\bin"
# 
# # GCC ARM
# #GCC_ARM_PATH = "../content/GCC-ARM/gcc-arm-none-eabi-9-2019-q4-major\bin"
# 
# # GCC CodeRed
# #GCC_CR_PATH = "../content/GCC-ARM/gcc-arm-none-eabi-9-2019-q4-major\bin"
# 
# # IAR
# #IAR_PATH = ""
# 
# # Goanna static analyser. Please overload it in private_settings.py
# #GOANNA_PATH = ""
# 
# #BUILD_OPTIONS = []
# 
# # mbed.org username
# #MBED_ORG_USER = ""
# 
# # Print compiler warnings and errors as link format
# #PRINT_COMPILER_OUTPUT_AS_LINK = False

!cat mbed_settings.py

pwd

cd GCC-ARM

ls

cd gcc-arm-none-eabi-9-2019-q4-major/

cd .

cd CMSISNN_Webinar/cmsisnn_demo

ls /content/GCC-ARM/gcc-arm-none-eabi-9-2019-q4-major/arm-none-eabi

!mbed config --list

!mbed config -G GCC_ARM_PATH "/content/GCC-ARM/gcc-arm-none-eabi-9-2019-q4-major/bin"

!pip uninstall werkzeug

!pip install --upgrade werkzeug==0.14.1

!mbed compile -m DISCO_F746NG -t GCC_ARM --source . --source ../ML-examples/cmsisnn-cifar10/camera_demo/camera_app/